### ISSUE TITLE
Sql Connection

### ISSUE THREAD

**Issue by bhasanoglu** [emregedikoglu/Pet-Clinic-Appointment-System#2]
SQL connection is not synchronizing when a new pet added. It synchronizes when SQL is restarted.

**Comment by J4hk** [comment]
I have same problem.

**Comment by emregedikoglu** [comment]
spring.datasource.url=jdbc:mysql://localhost/petclinic
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.jdbc.Driver

You must add the above code into the application.properties file. You must make your own username and password.

**Comment by damlayildirim** [comment]
Thank you

**Comment by J4hk** [comment]
Thanks man!
